### ISSUE TITLE
Dati regionali non più funzionanti

### ISSUE THREAD

**Issue by AndreaCallia** [SimoneTinella/Stato_COVID19_Italia_Android#2]
Ciao @SimoneTinella , prima di tutto ti ringrazio per questa bellissima app...

Ho notato che i dati regionali non funzionano più (quando seleziono una qualunque regione l'app va in crash ed esce improvvisamente), e immagino che possa dipendere da uno di questi due fattori:

1. La struttura dei dati sul sito della Protezione Civile è cambiata e l'app non riesce a fare più lo scraping come prima;
2. Alcune correzioni fatte dalle regioni, che hanno fatto "diminuire" il numero di contagiati totali (che non dovrebbe mai diminuire) sia nelle regioni che nelle provincie, fa andare in tilt l'app, perché magari non si aspetta dei numeri negativi quando legge i dati corrispondenti.

Cosa ne pensi? Pensi si possa fare qualcosa? Purtroppo non posso fare il debug dell'app perché non sono molto esperto come android, ma se sai già quali parti del codice sono influenzate posso darti una mano a modificarlo...

**Comment by SimoneTinella** [comment]
Ciao @AndreaCallia , grazie mille per la segnalazione e per il supporto offerto. 

Mi attivo per capire il problema e apportare il relativo fix ;-)

**Comment by AndreaCallia** [comment]
Grazie gentilissimo :-)

**Comment by SimoneTinella** [comment]
@AndreaCallia Ho rilasciato il fix con la versione 1.2.3.

La causa del problema è stata una modifica al dataset Provinciale. Hanno separato i record con denominazione "In fase di defizione/aggiornamento" senza bonificare i precedenti. Questo ha provocato il crash nell'app per via della mancanza di alcuni mapping (l'app si aspetta lo stesso numero di record per ogni denominazione). Ho temporaneamente risolto accorpando le due denominazioni in una sola.

Dagli avvisi presenti nel repository della PC leggo che nei prossimi giorni la struttura cambierà ulteriormente... Farò ulteriori verifiche per la ricerca di eventuali nuove incompatibilità.

Ti ringrazio ancora per avermi segnalato il problema ;)

**Comment by AndreaCallia** [comment]
Grazie infinite per questo! :) 
Ti volevo dire, visto che non sono mai riuscito ad installare l'APK direttamente da qui (forse per motivi di compatibilità?) ma solo tramite f-droid, metterai l'aggiornamento corrispondente a questo fix anche su f-droid?

Grazie ancora...

**Comment by SimoneTinella** [comment]
L'aggiornamento arriverà anche su f-droid ma i tempi di rilascio su quello store non dipendono da me. Per installarlo da qui devi prima disinstallare la versione di f-droid (i due apk vengono generati con chiavi diverse e sono quindi incompatibili)

**Comment by AndreaCallia** [comment]
Ah grazie per questa preziosissima informazione!!
