### ISSUE TITLE
Cache downloaded data

### ISSUE THREAD

**Issue by erdmark** [SimoneTinella/Stato_COVID19_Italia_Android#7]
The app loads all data again on every startup. This often needs 30 seconds on my phone, downloads circa 1mB and needs longer when on a slow connection.
Because the data gets updated only once a day it is not necessary to reload on every startup.

Possible solutions:
1. Save previous data and only reload when the user does it manually
2. Ask for example a server if there is new data and only reload if there is new data
3. Reload only after a few hours
4. Reload weh data is from yesterday or older and it is after 18:30 in the evening
5. Only download new data

Used app version: 1.2.4.1

**Comment by SimoneTinella** [comment]
Hi @erdmark , thanks for reporting. A cache layer will be added in the next release.

**Comment by SimoneTinella** [comment]
This feature has been released in version 1.2.5
