### ISSUE TITLE
Zoom axles separately

### ISSUE THREAD

**Issue by erdmark** [SimoneTinella/Stato_COVID19_Italia_Android#8]
Currently you can zoom into "Grafico Temporale", but it always zooms with both axis. It would be nice to zoom in for example only with the number of cases to compare how many infections were in summer. Currently you see only that it is almost 0 or you see only a few dates when zooming in.

Possible solution: using pinch zoom with the fingers on the far right side of the screen zooms the numbers, pinch-zoom on the bottom zooms the dates, pinch-zoom in the middle is like now zooming both axis.

Used app version: 1.2.4.1

**Comment by SimoneTinella** [comment]
Released on app version 1.2.8
